#created on: Apr 9, 2012
package com.sample

#list any import classes here.
import com.sample.ReconciliationBean;
import com.sample.RuleDVO;

#declare any global variables here

rule "MOD/HEREFI - Verify QPC/AR indicators are populated with Y, N, E, or I "
	when 		
		$a : ReconciliationBean(qpcarIndicator != "II" && != "YI" && != "NI" && != "YE" && != "YY" && != "YN" && != "NE" && != "NY" && != "NN")
		$b : ReconciliationBean(eventMap : eventMap, alertsList : alertsList)
		$ruleDVO : RuleDVO()		
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("42");
		$ruleDVO.setFieldOldVale($a.getQpcarIndicator());
		$ruleDVO.setFieldName("qpcarIndicator");		
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);
end

rule "MOD/HEREFI - Verify Slid Code = HAREFI OR Doc Cust is Not Null"
	when 
		$a : ReconciliationBean(slidCode == "HAREFI" || docCust != null)
		$b : ReconciliationBean(eventMap : eventMap,  alertsList : alertsList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("46");
		$ruleDVO.setFieldOldVale($a.getSlidCode());
		$ruleDVO.setFieldName("slidCode");	
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);
end 

rule "MOD/HEREFI - If phone flag equal to 4 and HAMA Indicator is equal to Y, update phone flag to 2 "
	when 
		$a : ReconciliationBean(phoneFlag == "4" && hamaIndicator == "Y")
		$b : ReconciliationBean(eventMap : eventMap, correctionsList : correctionsList, shawUpdatesList : shawUpdatesList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("43");
		$ruleDVO.setFieldOldVale($a.getPhoneFlag());
		$ruleDVO.setFieldNewValue("2");
		$ruleDVO.setFieldName("phoneFlag");
		correctionsList.add($ruleDVO);
		shawUpdatesList.add($ruleDVO);
		eventMap.put("CORRETCIONS", correctionsList);
		eventMap.put("SHAWUPDATES", shawUpdatesList);
end 

rule "MOD/HEREFI - Verify Phone Flag, on LCA, is 2 - Report an Alert"
	when 
		$a : ReconciliationBean(phoneFlag == "2")
		$b : ReconciliationBean(eventMap : eventMap, alertsList : alertsList)
		$ruleDVO : RuleDVO()			
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("43A");
		$ruleDVO.setFieldOldVale($a.getPhoneFlag());
		$ruleDVO.setFieldName("phoneFlag");
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);
end 

function void log(String name) {
	System.out.println(name);
}

