#created on: Apr 20, 2012
package com.sample

#list any import classes here.
import com.sample.ReconciliationBean;
import com.sample.RuleDVO;

rule "TLL-If phone flag equal to 4 and HAMA Indicator is equal to Y, update phone flag to 2 "
	when 
		$a : ReconciliationBean(phoneFlag == "4" && hamaIndicator == "Y")
		$b : ReconciliationBean(eventMap : eventMap, correctionsList : correctionsList, shawUpdatesList : shawUpdatesList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("28");
		$ruleDVO.setFieldOldVale($a.getPhoneFlag());
		$ruleDVO.setFieldNewValue("2");
		$ruleDVO.setFieldName("phoneFlag");
		correctionsList.add($ruleDVO);
		shawUpdatesList.add($ruleDVO);
		eventMap.put("CORRETCIONS", correctionsList);
		eventMap.put("SHAWUPDATES", shawUpdatesList);
end 

rule "TLL-Verify Phone Flag, on LCA, is 2 - Report an Alert"
	when 
		$a : ReconciliationBean(phoneFlag == "2")
		$b : ReconciliationBean(eventMap : eventMap, alertsList : alertsList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("11");
		$ruleDVO.setFieldOldVale($a.getPhoneFlag());
		$ruleDVO.setFieldName("phoneFlag");		
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);
end

rule "TLL-Appraisal Type, on LCA, should not be blank or null"
	when 
		$a : ReconciliationBean(appraisalType == "" || appraisalType == null)
		$b : ReconciliationBean(eventMap : eventMap, alertsList : alertsList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("29");
		$ruleDVO.setFieldOldVale($a.getAppraisalType());
		$ruleDVO.setFieldName("appraisalType");		
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);
end

rule "TLL-Verify Property Value = 0"
	when 
		$a : ReconciliationBean( (propertyValue == 0) && (appraisedValue == 0 || purchasePrice == 0) )
		$b : ReconciliationBean(eventMap : eventMap, alertsList : alertsList)
		$ruleDVO : RuleDVO()
	then 
		$ruleDVO = new RuleDVO();
		$ruleDVO.setExceptioncode("30");
		$ruleDVO.setFieldOldVale($a.getPropertyValue() + "");
		$ruleDVO.setFieldName("propertyValue");	
		alertsList.add($ruleDVO);
		eventMap.put("ALERTS", alertsList);	
end

